### ISSUE TITLE
Extend/Imrpove chirp/sound when pausing

### ISSUE THREAD

**Issue by shermzm** [inanutshellus/cura-plugin-pause-at-height-filament-swap#1]
This makes a very small "chirp" when the pause command begins. It would be very nice if we could somehow use the system sounds to play a longer/louder beep to get someone's attention. 

As it stands now I just set Cura to use a 150s timer, which is plenty of time to hit pause if I don't notice right away, or change the filament completely if I do!

**Comment by inanutshellus** [comment]
Sure, good idea. If you get the latest version, there's now a new option to choose the extended melody.

For posterity, I grabbed the melody from user `mazmoon` on Thingiverse. See: https://www.thingiverse.com/thing:446853

**Comment by inanutshellus** [comment]
BTW - It occurs to me that you said all it does is make a "small chirp". The music it plays is the first few notes to the Indiana Jones theme. If all you're hearing is a single short chirp currently, your printer may not be capable of playing the full range of music notes.

**Comment by shermzm** [comment]
I have the Anycubic i3 Mega S and come to think of it, I've only ever heard it play one note, so it must be a limitation of the printer.

**Comment by inanutshellus** [comment]
An Anycubic Mega should be able to play the tones. Perhaps your firmware could use updating. 

Try hooking your printer up to a PC and run this on your printer using Pronterface:

M300 S1318 P240
M300 S0 P120
M300 S1396 P120
M300 S1567 P120
M300 S0 P120
M300 S2093 P720

... if each command produces a different tone, you're good. If not... the issue is your printer and I'd suggest looking into updating the firmware.
